# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 550173b2439017cee9801f2b8306a2aec774e4146bf1e5ef10ab43985ede588cf850d50f820ae71dd204aac499775702d4db1674093b338775a4bff018ed7c77

test:
  secret_key_base: 1ad5a77fb0601bac50a8704aae404230dada2b0b5d4e5c5f278b602ef33f2b81009ecf76ada18e1151c69093156c0dab1cd991f7da4dea754b7294cd49e6d321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
